drivers/misc: mediatek: typec: Disable unused werror
drivers/misc/mediatek/typec/tcpc/tcpc_rt1711h.c:811:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int ret;

Signed-off-by: Egii <regidesoftian@gmail.com>